# Generated by Django 3.2.15 on 2022-09-05 07:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dataview_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemetadata',
            name='last_modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
