# Generated by Django 3.2.15 on 2022-09-01 05:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileMetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=100)),
                ('uploaded_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('data_cleaning', models.BooleanField(default=False)),
                ('total_cols', models.PositiveIntegerField()),
            ],
        ),
    ]
