# Generated by Django 3.2.15 on 2022-09-01 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemetadata',
            name='column_headers',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
